name: DevOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Application Version
        id: semver-app
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true

      - name: Debug Version Output
        run: echo "Version is ${{ steps.semver-app.outputs.version }}"

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          VERSION=${{ steps.semver-app.outputs.version }}

          docker build \
           -t ghcr.io/$REPO_NAME:staging \
           -t ghcr.io/$REPO_NAME:$VERSION \
           -f DevOpsWebApplication/Dockerfile \
           .

          docker push ghcr.io/$REPO_NAME:staging
          docker push ghcr.io/$REPO_NAME:$VERSION

      - name: Create Release Notes 
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semver-app.outputs.version }}
          generateReleaseNotes: true
          body: |
            This release includes the following container image:
            https://ghcr.io/${{ github.repository }}:${{ steps.semver-app.outputs.version }}