name: DevOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        REPO_NAME=$(echo "JannickWAndresen/devops_webapplication" | tr '[:upper:]' '[:lower:]')
        docker buildx build \
        -t ghcr.io/$REPO_NAME:staging \
        -t ghcr.io/$REPO_NAME:0.0.1 \
        -f DevOpsWebApplication/Dockerfile \
        .  # Adding the missing context path here
        docker push ghcr.io/$REPO_NAME --all-tags
        - name: Create Release Notes 
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ steps.semver-app.outputs.version }}
          generateReleaseNotes: true
          body: |
            This release includes the following container image:
            http://ghcr.io/${{ github.repository }}:${{ steps.semver-app.outputs.version }}
